# Generated by Django 4.1.5 on 2023-01-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_Registration_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainer_fname', models.CharField(max_length=30)),
                ('complainer_lname', models.CharField(max_length=40)),
                ('complaint_title', models.CharField(max_length=60)),
                ('complaint_timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint_details', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Registration_Table_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=30)),
                ('complaint_title', models.CharField(max_length=60)),
                ('complainer_fname', models.CharField(max_length=30)),
                ('complainer_lname', models.CharField(max_length=40)),
                ('complainer_email', models.EmailField(max_length=254)),
                ('complaint_details', models.CharField(max_length=5000)),
                ('complaint_timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint_proof', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint_Management_System',
        ),
    ]
