# Generated by Django 4.1.5 on 2023-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints_Registration_Table',
            fields=[
                ('complainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_id', models.CharField(max_length=30)),
                ('complainer_role', models.CharField(max_length=20)),
                ('complainer_fname', models.CharField(max_length=30)),
                ('complainer_lname', models.CharField(max_length=40)),
                ('complaint_title', models.CharField(max_length=60)),
                ('complainer_contact', models.IntegerField(max_length=10)),
                ('complainer_email', models.EmailField(max_length=254)),
                ('complaint_timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint_details', models.CharField(max_length=5000)),
                ('complaint_proof', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint_Registration_Table',
        ),
    ]
