# Generated by Django 4.1.5 on 2023-01-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints_Registration_Table',
        ),
    ]
